services:
  # backend service
  # backend-service:
  #   build:
  #     context: ../backend
  #     dockerfile: Dockerfile
  #   container_name: movie_backend
  #   ports:
  #     - '8081:8081'
  #   environment:
  #     - NODE_ENV=development
  #     - APP_PORT=8081
  #     - DB_TYPE=postgres
  #     - DB_HOST=db
  #     - DB_PORT=5432
  #     - DB_USERNAME=postgres
  #     - DB_PASSWORD=123456
  #     - DB_NAME=nestjs_db
  #     - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
  #     - SERVICE_NAME=backend-service
  #     - OTEL_EXPORTER_URL=http://localhost:4317
  #   networks:
  #     - movie-network
  #   depends_on:
  #     - db
  #     - rabbitmq

  # ai service
  # ai-service:
  #   build:
  #     context: ./ai-service
  #     dockerfile: Dockerfile # FROM python:3.11-slim
  #   ports:
  #     - '8082:8082'
  #   networks:
  #     - movie-net
  #   environment:
  #     - APP_PORT=8082
  #     - VECTOR_DB_URL=xxxx
  #     - SERVICE_NAME=ai-service
  #     - OTEL_EXPORTER_URL=http://localhost:4317
  #     - RABBITMQ_URL=amqp://guest:guest@localhost:5672

  # db
  db:
    image: postgres:15-alpine
    container_name: postgres_db
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: nestjs_db
      TZ: Asia/Ho_Chi_Minh
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - movie-network

  # vector db

  # caching
  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    networks:
      - movie-network

  # message broker
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672' # RabbitMQ Management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - movie-network

networks:
  movie-network:
    driver: bridge

volumes:
  db-data:
    driver: local
  redis_data:
    driver: local
  rabbitmq_data:
    driver: local
