input {
  tcp {
    port => 5000
    codec => json
  }
}

output {
  elasticsearch {
    hosts => ["elasticsearch:9200"]
    index => "nestjs-docker-logs-%{+YYYY.MM.dd}"
  }
  
  stdout { codec => rubydebug } 
}
